---
apiVersion: v1
kind: Pod
metadata:
  name: c1
  namespace: tiru
  labels:
    app: alpine
spec:
  containers:
    - name: alpine-contianer
      image: alpine:latest
      command: ["/bin/sh"]
      args: ["-c", "sleep 3600"]
---
apiVersion: v1
kind: Namespace
metadata:
  name: my-alpine
  namespace: tiru