apiVersion: v1
kind: Deployment
metadata:
  name: nop-deployment
  labels:
    app: nop
    purpose: deployment
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: nop
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nop
        version: v1.1
    spec:
      containers:
        - name: nopCommerce
          image: dockertiru/nopcommerce2309
          ports:
            - containerPort: 80
              protocol: TCP